const SITE = {
  _SITE_ID: '',
  ALIAS: '',
  AREA: '',
  CLUSTER_ID: '',
  CLUSTER_NAME: '',
  OPERATOR: '',
  OWNER: '',
  REGION: '',
  SITE_NAME: '',
  SITE_TYPE: '',
  _LOCATION: {
    GEO: {
      EASTING: '',
      NORTHING: '',
    },
    ADDRESS: {
      ADR1: '',
      ADR2: '',
      ADR3: '',
      TOWN: '',
      COUNTY: '',
      POSTCODE: '',
    },
  },
  _SITE_CUSTOM: {
    AREA_OP: '',
    AREA_OWNER: '',
    MOBILE_OPTIMISER: '',
    RADIOMANAGER: '',
    MOBILE_RADIOMANAGER: '',
    AREA: '',
    REGION_2: '',
    JV_ID: '',
  },
  _SECTORS: [
    {
      _SECTOR_ID: '',
      ENODEB_ID: '',
      ENODEBNAME: '',
      ANTENNA_NUMBER: '',
      _SECTOR_CUSTOM: {
        ENVIRONMENT: '',
        SITE_GENERATION_TYPE: '',
      },
      _ANTENNAS: [
        {
          _ANTENNA_ID: '',
          ANTENNA_HEIGHT: '',
          ANTENNA_NAME: '',
          AZIMUTH: '',
          BEAMWIDTH_H: '',
          GROUND_HEIGHT: '',
          MHA: '',
          TILT_ELEC: '',
          TILT_MECH: '',
          _CELLS: [
            {
              _CELL_ID: '',
              _CELL_REF: '',
              ARFCN: '',
              CELL_TYPE: '',
              LAYER: '',
              TECH_GEN: '',
              TX_LOSS: '',
              TX_POWER: '',
              MODEL_NAME: '',
              MANUFACTURER: '',
              NE_ID: '',
              OMC_NE_NAME: '',
              MSC: '',
              OMC_ID: '',
              CIRCUIT: '',
              CELL_CARRIERS: '',
              CALL_SAVER_CODE: '',
              CELL_OF_ORIGIN: '',
              ZONE_CODE: '',
              KIT_TYPE: '',
              BIS_DATE: '',
              CELL_OWNER: '',
              CELL_SEQ_NO: '',
              PSEUDO_CARRIERS: '',
              PCI: '',
              RSI: '',
              TAC: '',
              _CELL_CUSTOM: {
                MODEL_NAME: '',
                MANUFACTURER: '',
                NE_ID: '',
                OMC_NE_NAME: '',
                MSC: '',
                OMC_ID: '',
                CIRCUIT: '',
                CELL_CARRIERS: '',
                CALL_SAVER_CODE: '',
                CELL_OF_ORIGIN: '',
                ZONE_CODE: '',
                KIT_TYPE: '',
                BIS_DATE: '',
                CELL_OWNER: '',
                CELL_SEQ_NO: '',
                PSEUDO_CARRIERS: '',
              }
            }, // LTE CELL
            {
              _CELL_ID: '',
              _CELL_REF: '',
              ARFCN: '',
              CELL_TYPE: '',
              LAYER: '',
              TECH_GEN: '',
              TX_LOSS: '',
              TX_POWER: '',
              OSS_CELLID: '',
              MODEL_NAME: '',
              MANUFACTURER: '',
              NE_ID: '',
              OMC_NE_NAME: '',
              MSC: '',
              OMC_ID: '',
              CIRCUIT: '',
              CELL_CARRIERS: '',
              CALL_SAVER_CODE: '',
              CELL_OF_ORIGIN: '',
              ZONE_CODE: '',
              KIT_TYPE: '',
              BIS_DATE: '',
              CELL_OWNER: '',
              CELL_SEQ_NO: '',
              PSEUDO_CARRIERS: '',
              LAC: '',
              PSC: '',
              RAC: '',
              SAC: '',
              URA: '',
              _CELL_CUSTOM: {
                OSS_CELLID: '',
                MODEL_NAME: '',
                MANUFACTURER: '',
                NE_ID: '',
                OMC_NE_NAME: '',
                MSC: '',
                OMC_ID: '',
                CIRCUIT: '',
                CELL_CARRIERS: '',
                CALL_SAVER_CODE: '',
                CELL_OF_ORIGIN: '',
                ZONE_CODE: '',
                KIT_TYPE: '',
                BIS_DATE: '',
                CELL_OWNER: '',
                CELL_SEQ_NO: '',
                PSEUDO_CARRIERS: '',
              }
            }, // WCDMA CELL
            {
              _CELL_ID: '',
              _CELL_REF: '',
              ARFCN: '',
              CELL_TYPE: '',
              LAYER: '',
              TECH_GEN: '',
              TX_LOSS: '',
              TX_POWER: '',
              BCF_INT_ID: '',
              BTS_INT_ID: '',
              MODEL_NAME: '',
              MANUFACTURER: '',
              NE_ID: '',
              OMC_NE_NAME: '',
              MSC: '',
              OMC_ID: '',
              CIRCUIT: '',
              CELL_CARRIERS: '',
              CALL_SAVER_CODE: '',
              CELL_OF_ORIGIN: '',
              ZONE_CODE: '',
              KIT_TYPE: '',
              BIS_DATE: '',
              CELL_OWNER: '',
              CELL_SEQ_NO: '',
              PSEUDO_CARRIERS: '',
              BSC_C_NUMBER: '',
              LAC: '',
              NCC: '',
              RAC: '',
              TRX_LIST: '',
              URA: '',
              BCC: '',
              BCCH: '',
              _CELL_CUSTOM: {
                BCF_INT_ID: '',
                BTS_INT_ID: '',
                MODEL_NAME: '',
                MANUFACTURER: '',
                NE_ID: '',
                OMC_NE_NAME: '',
                MSC: '',
                OMC_ID: '',
                CIRCUIT: '',
                CELL_CARRIERS: '',
                CALL_SAVER_CODE: '',
                CELL_OF_ORIGIN: '',
                ZONE_CODE: '',
                KIT_TYPE: '',
                BIS_DATE: '',
                CELL_OWNER: '',
                CELL_SEQ_NO: '',
                PSEUDO_CARRIERS: '',
                BSC_C_NUMBER: '',
              }
            }, // GSM CELL
          ]
        }, // ANTENNA
        {} // ANTENNA
      ]
    }, // SECTOR
    {}, // SECTOR
    {}, // SECTOR
  ]
}; // SITE
